i18n messages sending support
HaHaWTH/AuthMeReReloaded pull request #155
Opened 2024-05-28 16:18 UTC by Dreeam-qwq

Send different languages of messages based on player's client setting, closes #153 .

TODOs:

- [ ] Complete missing keys in message/help file.
- [ ] Finish mapping between locale and authme config translation code

2024-05-28 19:02 UTC, F3F5 commented
wow

2024-05-29 17:11 UTC, F3F5 commented
the current problem is one 
- session is enabled, I log in to the server (no translation), but when I write commands - translation is there 
when I log in again, there is no translation
when switching on the server - 
![rejoin](https://github.com/HaHaWTH/AuthMeReReloaded/assets/170719238/a1542978-ef45-4847-945d-0f1a23e59e9a)
![restart](https://github.com/HaHaWTH/AuthMeReReloaded/assets/170719238/be31fd16-5f4e-4ee8-8962-47edcf4f7a19)
partial translation (only when logging in, for commands, etc. everything is fine).

2024-05-31 15:14 UTC, Dreeam-qwq commented
> ```
>     // LOCALE_MAP.put("zhmc", "zhmc");
> ```
> 
> why

Because Minecraft didn't have this locale, refer to https://minecraft.wiki/w/Language

2024-06-01 11:04 UTC, F3F5 commented
![Screenshot_1](https://github.com/HaHaWTH/AuthMeReReloaded/assets/170719238/8ea1408a-b4eb-41a3-a622-dd68d836fcf3)

2024-06-01 11:05 UTC, F3F5 commented
Also, there's no translation for /register

2024-06-02 11:14 UTC, F3F5 commented
@Dreeam-qwq testing.

2024-06-02 11:22 UTC, F3F5 commented
![Screenshot_1](https://github.com/HaHaWTH/AuthMeReReloaded/assets/170719238/cbaab5f4-3be2-4737-9934-1b94f70eb035)

2024-06-02 11:23 UTC, F3F5 commented
but rejoin now with translation, only register/login message need fix @Dreeam-qwq

2024-06-02 12:44 UTC, HaHaWTH commented
> ![Screenshot_1](https://private-user-images.githubusercontent.com/170719238/335860987-cbaab5f4-3be2-4737-9934-1b94f70eb035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzI1MDEsIm5iZiI6MTcxNzMzMjIwMSwicGF0aCI6Ii8xNzA3MTkyMzgvMzM1ODYwOTg3LWNiYWFiNWY0LTNiZTItNDczNy05OTM0LTFiOTRmNzBlYjAzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTI1M2VmNjkyZDJlMGVjNzE3MzIyNWMzZTE1OWNlYWUyZTg5NWViNjdhZmM5ZDhkNWRmNTJkMzkyYmI4MzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v_GNvB2X7PCuWLvNL_Gp0wnNuSP6mQUp9FqOYfwFFKY)

What's your client & server version?

2024-06-02 13:14 UTC, F3F5 commented
> > ![Screenshot_1](https://private-user-images.githubusercontent.com/170719238/335860987-cbaab5f4-3be2-4737-9934-1b94f70eb035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzI1MDEsIm5iZiI6MTcxNzMzMjIwMSwicGF0aCI6Ii8xNzA3MTkyMzgvMzM1ODYwOTg3LWNiYWFiNWY0LTNiZTItNDczNy05OTM0LTFiOTRmNzBlYjAzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTI1M2VmNjkyZDJlMGVjNzE3MzIyNWMzZTE1OWNlYWUyZTg5NWViNjdhZmM5ZDhkNWRmNTJkMzkyYmI4MzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v_GNvB2X7PCuWLvNL_Gp0wnNuSP6mQUp9FqOYfwFFKY)
> 
> What's your client & server version?

1.8.8

2024-06-02 13:24 UTC, Dreeam-qwq commented
> ![Screenshot_1](https://private-user-images.githubusercontent.com/170719238/335860987-cbaab5f4-3be2-4737-9934-1b94f70eb035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzQ3MTgsIm5iZiI6MTcxNzMzNDQxOCwicGF0aCI6Ii8xNzA3MTkyMzgvMzM1ODYwOTg3LWNiYWFiNWY0LTNiZTItNDczNy05OTM0LTFiOTRmNzBlYjAzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMzIwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzZlYzk1YWE4NmE3ZWQ3NTQ3MjgyZjBlZDg5MzJlZTIyODQ1YzQ5ZDk4NDZjODJlM2Y4NmM1YzVhZGU0NTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DRtcqcNxeqylzUACdI03UlWy1o3vt0uTr5XOCQR3qwg)

Delete authme messages folder and try latest build of this pullrequest again.

2024-06-02 22:29 UTC, F3F5 commented
change language at the moment of authorization , /register when it will write again - translation is old. but other commands are in another language
![Screenshot_1](https://github.com/HaHaWTH/AuthMeReReloaded/assets/170719238/a91d3fd8-765a-4022-8d3a-a72d08149c41)

2024-06-02 22:29 UTC, F3F5 commented
1.20.6 client

2024-06-03 11:16 UTC, HaHaWTH requested changes

2024-06-03 11:16 UTC, HaHaWTH commented on src/main/java/fr/xephi/authme/util/Utils.java
`majorVersion` and` minorVersion` should be uppercase, like `MAJOR_VERSION`.

2024-06-03 11:16 UTC, HaHaWTH commented on src/main/resources/messages/messages_bg.yml
gui captcha related messages should be removed, sorry about that🥲

2024-06-03 11:16 UTC, HaHaWTH commented on src/main/java/fr/xephi/authme/util/message/I18NUtils.java
I prefer directly return null instead of blocking for 0.5 seconds here. A fallback is needed huh?

2024-06-03 12:09 UTC, Dreeam-qwq commented on src/main/java/fr/xephi/authme/util/message/I18NUtils.java
For now, it will directly return null if no locale packet received before calling `getLocale()`, and there is a null check in `getMessageByLocale()`, use original `getMessage()` method if the locale is null.

2024-06-03 15:55 UTC, merged

2024-06-03 15:56 UTC, HaHaWTH commented
Thanks! Really appreciate *^o^*