Better Regex e-mail
HaHaWTH/AuthMeReReloaded pull request #186
Opened 2024-07-22 22:10 UTC by luketeam5

The current Regex e-mail doesn't account for people in other countries (for example, in my country `@seznam.cz` is a popular e-mail!) or custom e-mails at that (`@luketeam5.xyz`)

I think it's better to allow any valid-looking e-mail addresses as default rather than restrict to popular mail providers only.
If someone wants to restrict to g-mail, outlook, ... they can do so manually, that's what the config is for after all.
But should allow all e-mail out of the box.

2024-07-22 23:58 UTC, HaHaWTH requested changes

2024-07-22 23:58 UTC, HaHaWTH commented on src/main/java/fr/xephi/authme/settings/properties/RestrictionSettings.java
Compile is failed cuz you deleted a backslash before the dot.
Add it back then we can run correctly!

2024-07-23 01:34 UTC, luketeam5 commented on src/main/java/fr/xephi/authme/settings/properties/RestrictionSettings.java
fixed, didn't copy the change properly

2024-07-23 01:39 UTC, HaHaWTH approved these changes

2024-07-23 01:39 UTC, merged