Add Email Verification
HaHaWTH/AuthMeReReloaded pull request #237
Opened 2024-12-10 01:14 UTC by Deichor

### Summary

I have implemented a feature to enforce email verification and allow specifying a column for this purpose.  

### Changes Introduced
- **Two new settings have been added:**
  - `kickNotVerified`: Prevents users with unverified emails from logging into the server.
  - `mySQLVerifiedField`: Specifies the name of the field in the database to be checked for email verification.

- **Additional Updates:**
  - Ensured compatibility with various database systems and conducted thorough testing. No issues were observed during the tests.
  - Did not add functionality to kick users immediately after registering, as this feature already exists. The new settings are designed to be combined for flexibility.
  - Updated the repository URL and version of **MultiverseCore**, as its repository has changed.
  - Updated the Log4J version to the latest one.

### Notes
- These changes aim to improve flexibility and ensure better integration with email verification systems.  
- The updates for MultiverseCore and Log4J address issues with outdated dependencies.

2024-12-10 03:38 UTC, rautamiekka requested changes

2024-12-10 03:38 UTC, rautamiekka commented on src/main/java/fr/xephi/authme/listener/PlayerListener.java
> +            final boolean isAuthAvailable= auth != null;
```suggestion
            final boolean isAuthAvailable = auth != null;
```

2024-12-10 11:19 UTC, HaHaWTH requested changes

2024-12-10 11:19 UTC, HaHaWTH commented on src/main/java/fr/xephi/authme/message/MessageKey.java
Should be changed to `email.unverified_kick`

2024-12-10 11:19 UTC, HaHaWTH commented on src/main/java/fr/xephi/authme/settings/properties/RestrictionSettings.java
> +    @Comment("Should unregistered players be kicked immediately?")
Here should be `unverified`, just like changes in docs/config.md

2024-12-10 11:19 UTC, HaHaWTH commented on src/main/resources/messages/messages_en.yml
Can you add this message key to other language files? Translator usage is fine, or I can do it later🙂

2024-12-10 18:15 UTC, HaHaWTH commented on src/main/resources/messages/messages_fi.yml
Here should be `unverified_kick`, just like other lang files

2024-12-10 18:16 UTC, HaHaWTH commented on src/main/resources/messages/messages_eu.yml
Same as messages_fi.yml

2024-12-10 19:59 UTC, HaHaWTH approved these changes

2024-12-11 11:39 UTC, HaHaWTH commented
Merged, thanks!

2024-12-11 11:40 UTC, merged